issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
